mybatis-flex:
  seata-config:
    enable: true #启动seata
    seata-mode: XA #XA或者AT
  datasource:
    accountdb:
      url: jdbc:mysql://127.0.0.1:3306/db_account
      username: root
      password: 123456
      break-after-acquire-failure: true
    orderdb:
      url: jdbc:mysql://127.0.0.1:3306/db_order
      username: root
      password: 123456
      break-after-acquire-failure: true
    stockdb:
      url: jdbc:mysql://127.0.0.1:3306/db_stock
      username: root
      password: 123456
      break-after-acquire-failure: true
server:
  port: 2010
seata:
  enabled: true
  application-id: business-service
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: false  #必须
#  use-jdk-proxy: false
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    #enable-degrade: false
    #disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: file
  registry:
    type: file
